version: "3.8"
services:
  students-test-server:
    container_name: students-test-server
    image: "students_test.jar"
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://students-test-db:${DB_PORT}/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      PORT: ${APP_LOCAL_PORT}
    ports:
      - ${APP_LOCAL_PORT}:${APP_EXTERNAL_PORT}

  students-test-db:
    container_name: students-test-db
    image: postgres:14-alpine3.14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: